// packages/vue-cli-plugin-typescript/generator/template/src/components/ResultLink.vue
<template>
  <a
    @click="onSelect"
    @contextmenu="onSelect"
    @mousedown="onSelect"
    @mouseup="onSelect"
    @touchstart="beginDelayedSelect"
    @touchend="cancelPendingSelect"
    :href="filteredUri"
    >{{ this.result.title }}</a
  >
</template>

<script lang="ts">
import Vue from 'vue';
import {buildInteractiveResult, Result} from '@coveo/headless';

export default Vue.extend({
  name: 'ResultLink',
  props: ['result'],
  data: function () {
    const interactiveResult = buildInteractiveResult(this.$root.$data.$engine, {
      options: {result: this.result as Result},
    });

    return {
      interactiveResult,
    };
  },
  computed: {
    filteredUri: function () {
      const uri = this.result.clickUri;
      // Filters out dangerous URIs that can create XSS attacks such as `javascript:`.
      const isAbsolute = /^(https?|ftp|file|mailto|tel):/i.test(uri);
      const isRelative = /^(\/|\.\/|\.\.\/)/.test(uri);
      return isAbsolute || isRelative ? uri : '';
    },
  },
  methods: {
    onSelect: function () {
      this.interactiveResult.select();
    },
    beginDelayedSelect: function () {
      this.interactiveResult.beginDelayedSelect();
    },
    cancelPendingSelect: function () {
      this.interactiveResult.cancelPendingSelect();
    },
  },
});
</script>

// packages/angular/src/ng-add-setup-project/files/src/app/result-link/result-link.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {
  buildInteractiveResult,
  InteractiveResult,
  Result,
} from '@coveo/headless';
import {EngineService} from '../engine.service';

@Component({
  selector: 'app-result-link',
  templateUrl: './result-link.component.html',
  styleUrls: ['./result-link.component.scss'],
})
export class ResultLinkComponent implements OnInit {
  private headlessInteractiveResult!: InteractiveResult;
  @Input() result!: Result;

  public constructor(private engineService: EngineService) {}

  private initializeController() {
    this.headlessInteractiveResult = buildInteractiveResult(
      this.engineService.get(),
      {options: {result: this.result}}
    );
  }

  public ngOnInit(): void {
    this.initializeController();
  }

  public get filteredUri() {
    const uri = this.result.clickUri;
    // Filters out dangerous URIs that can create XSS attacks such as `javascript:`.
    const isAbsolute = /^(https?|ftp|file|mailto|tel):/i.test(uri);
    const isRelative = /^(\/|\.\/|\.\.\/)/.test(uri);
    return isAbsolute || isRelative ? uri : '';
  }

  public select() {
    this.headlessInteractiveResult.select();
  }

  public beginDelayedSelect() {
    this.headlessInteractiveResult.beginDelayedSelect();
  }

  public cancelPendingSelect() {
    this.headlessInteractiveResult.cancelPendingSelect();
  }
}

<a
  href="{{ filteredUri }}"
  (click)="select()"
  (contextmenu)="select()"
  (mousedown)="select()"
  (touchstart)="beginDelayedSelect()"
  (touchend)="cancelPendingSelect()"
  >{{ result.title }}</a
>
