// packages/vue-cli-plugin-coveo/generator/template/src/components/ResultList.vue
<template>
  <section>
    <template v-if="state.isLoading">
      <div v-for="n in 5" class="my-5" :key="n">
        <div class="my-1">
          <b-skeleton :animated="true"></b-skeleton>
        </div>
        <b-skeleton :animated="true"></b-skeleton>
        <b-skeleton :animated="true"></b-skeleton>
        <b-skeleton :animated="true" width="50%"></b-skeleton>
      </div>
    </template>
    <template v-else>
      <div
        class="mb-6 py-2"
        v-for="result in state.results"
        :key="result.uniqueId"
      >
        <div class="is-size-5 mb-2">
          <a :href="result.clickUri">{{ result.title }}</a>
        </div>
        <p>{{ result.excerpt }}</p>
        <div class="columns">
          <div
            v-if="result.raw.author"
            class="mt-2 is-size-7 has-text-grey column is-narrow"
          >
            <b>Author</b> {{ result.raw.author }}
          </div>
          <div
            v-if="result.raw.source"
            class="mt-2 is-size-7 has-text-grey column is-narrow"
          >
            <b>Source</b> {{ result.raw.source }}
          </div>
          <div
            v-if="result.raw.objecttype"
            class="mt-2 is-size-7 has-text-grey column is-narrow"
          >
            <b>Object Type</b> {{ result.raw.objecttype }}
          </div>
        </div>
      </div>
    </template>
  </section>
</template>

<script>
import engine from '../Engine';
import {buildResultList, FieldActions} from '@coveo/headless';
export default {
  name: 'ResultList',
  data: function () {
    return {
      state: {},
    };
  },
  created: function () {
    const fieldsToLoad = ['objecttype', 'filetype', 'author'];
    engine.dispatch(FieldActions.registerFieldsToInclude(fieldsToLoad));

    this.resultList = buildResultList(engine);
    this.resultList.subscribe(() => {
      this.state = {...this.resultList.state};
    });
  },
};
</script>

// packages/angular/src/ng-add-setup-project/files/src/app/result-list/result-list.component.ts
import {Component, OnInit} from '@angular/core';
import {buildResultList, Result, ResultList} from '@coveo/headless';
import {engine} from '../engine';

@Component({
  selector: 'app-result-list',
  templateUrl: './result-list.component.html',
  styleUrls: ['./result-list.component.scss'],
})
export class ResultListComponent implements OnInit {
  private headlessResultList!: ResultList;

  constructor() {}

  get results(): Result[] {
    return this.headlessResultList.state.results;
  }

  private initializeController() {
    this.headlessResultList = buildResultList(engine);
  }

  ngOnInit(): void {
    this.initializeController();
  }
}

<div *ngFor="let result of results">
  <div class="mb-5">
    <div class="mb-2">
      <a href="{{ result.clickUri }}">{{ result.title }}</a>
    </div>

    <div class="mb-1">
      <div class="mat-body-1">{{ result.excerpt }}</div>
    </div>

    <div class="flex-row">
      <div class="mr-4">
        <div *ngIf="result.raw.source" class="mat-caption">
          <span class="mr-1">Source</span>
          <span>{{ result.raw.source }}</span>
        </div>
      </div>
      <div class="mr-4">
        <div *ngIf="result.raw.objecttype" class="mat-caption">
          <span class="mr-1">Object Type</span>
          <span>{{ result.raw.objecttype }}</span>
        </div>
      </div>
    </div>
  </div>
</div>
