// packages/vue-cli-plugin-coveo/generator/template/src/components/SearchBox.vue
<template>
  <b-autocomplete
    icon="magnify"
    placeholder="Search"
    :clearable="true"
    :data="suggestions"
    :open-on-focus="true"
    @typing="onTyping"
    @select="onSelect"
    @keydown.native="onKeyDown"
  ></b-autocomplete>
</template>

<script>
import engine from '../Engine';
import {buildSearchBox, SearchBoxOptions} from '@coveo/headless';

export default {
  name: 'SearchBox',
  data: function () {
    return {
      state: {},
    };
  },
  methods: {
    onTyping: function (v) {
      this.searchBox.updateText(v);
    },
    onSelect: function (v) {
      this.searchBox.selectSuggestion(v);
    },
    onKeyDown: function (e) {
      if (e.keyCode === 13) {
        this.searchBox.submit();
      }
    },
  },
  computed: {
    suggestions: function () {
      return this.state.suggestions.map((s) => s.rawValue);
    },
  },
  created: function () {
    const options = {
      numberOfSuggestions: 5,
    };
    this.searchBox = buildSearchBox(engine, {options});
    this.unsubscribe = this.searchBox.subscribe(() => {
      this.state = {...this.searchBox.state};
    });
  },
};
</script>

// packages/angular/src/ng-add-setup-project/files/src/app/search-box/search-box.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {buildSearchBox, SearchBox, SearchBoxOptions} from '@coveo/headless';
import {FormControl} from '@angular/forms';
import {engine} from '../engine';

@Component({
  selector: 'app-search-box',
  templateUrl: './search-box.component.html',
  styleUrls: ['./search-box.component.scss'],
})
export class SearchBoxComponent implements OnInit {
  headlessSearchBox: SearchBox;
  myControl = new FormControl();
  suggestions: {
    highlightedValue: string;
    rawValue: string;
  }[];

  constructor() {}

  updateState() {
    this.suggestions = this.headlessSearchBox.state.suggestions;
  }

  onSelect(value: string) {
    this.headlessSearchBox.selectSuggestion(value);
  }

  onInput() {
    this.headlessSearchBox.updateText(this.myControl.value);
  }

  onKeyDown(event) {
    if (event.keyCode === 13 && !this.headlessSearchBox.state.isLoading) {
      this.headlessSearchBox.submit();
      this.headlessSearchBox.hideSuggestions();
    }
  }

  private initializeController() {
    const options: SearchBoxOptions = {
      numberOfSuggestions: 3,
    };

    this.headlessSearchBox = buildSearchBox(engine, {
      options,
    });
  }

  ngOnInit() {
    this.initializeController();
    this.headlessSearchBox.subscribe(() => this.updateState());
  }
}

  <mat-form-field class="full-width">
    <input
      type="text"
      placeholder="Search"
      matInput
      (input)="onInput()"
      (keydown)="onKeyDown($event)"
      [formControl]="myControl"
      [matAutocomplete]="auto"
    />
    <mat-autocomplete #auto="matAutocomplete" (optionSelected)="onSelect($event.option.value)">
      <mat-option *ngFor="let suggestion of suggestions" [value]="suggestion.rawValue">
        {{ suggestion.rawValue }}
      </mat-option>
    </mat-autocomplete>
  </mat-form-field>
<!-- </form> -->
