// packages/cra-template/template/src/Components/SearchBox.tsx
import {FunctionComponent, useEffect, useState, useContext} from 'react';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import {
  buildSearchBox,
  SearchBox as HeadlessSearchBox,
  SearchBoxOptions,
} from '@coveo/headless';
import EngineContext from '../common/engineContext';

interface SearchBoxProps {
  controller: HeadlessSearchBox;
}

const SearchBoxRenderer: FunctionComponent<SearchBoxProps> = (props) => {
  const {controller} = props;
  const [state, setState] = useState(controller.state);

  useEffect(
    () => controller.subscribe(() => setState(controller.state)),
    [controller]
  );

  return (
    <Autocomplete
      inputValue={state.value}
      onInputChange={(_, newInputValue) => {
        controller.updateText(newInputValue);
      }}
      onChange={() => {
        controller.submit();
      }}
      options={state.suggestions.map((suggestion) => suggestion.rawValue)}
      freeSolo
      style={{width: 'auto'}}
      renderInput={(params) => (
        <TextField {...params} placeholder="Search" size="small" />
      )}
    />
  );
};

const SearchBox = () => {
  const options: SearchBoxOptions = {numberOfSuggestions: 8};
  const engine = useContext(EngineContext)!;
  const controller = buildSearchBox(engine, {options});
  return <SearchBoxRenderer controller={controller} />;
};

export default SearchBox;

// packages/vue-cli-plugin-typescript/generator/template/src/components/SearchBox.vue
<template>
  <b-autocomplete
    icon="magnify"
    placeholder="Search"
    :clearable="true"
    :data="suggestions"
    :open-on-focus="true"
    @typing="onTyping"
    @select="onSelect"
    @keydown.native="onKeyDown"
  ></b-autocomplete>
</template>

<script>
import {buildSearchBox} from '@coveo/headless';

export default {
  name: 'SearchBox',
  data: function () {
    return {
      state: {},
    };
  },
  methods: {
    onTyping: function (v) {
      this.searchBox.updateText(v);
    },
    onSelect: function (v) {
      this.searchBox.selectSuggestion(v);
    },
    onKeyDown: function (e) {
      if (e.keyCode === 13) {
        this.searchBox.submit();
      }
    },
  },
  computed: {
    suggestions: function () {
      return this.state.suggestions.map((s) => s.rawValue);
    },
  },
  created: function () {
    const options = {
      numberOfSuggestions: 5,
    };
    this.searchBox = buildSearchBox(this.engine, {options});
    this.unsubscribe = this.searchBox.subscribe(() => {
      this.state = {...this.searchBox.state};
    });
  },
};
</script>
