// packages/cra-template/template/src/Components/Pager.tsx
import {FunctionComponent, useEffect, useState, useContext} from 'react';
import {Pagination} from '@mui/material';
import {buildPager, Pager as HeadlessPager} from '@coveo/headless';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import EngineContext from '../common/engineContext';

interface PagerProps {
  controller: HeadlessPager;
}

const PagerRenderer: FunctionComponent<PagerProps> = (props) => {
  const {controller} = props;
  const [state, setState] = useState(controller.state);

  useEffect(
    () =>
      controller.subscribe(() =>
        setTimeout(() => setState(controller.state), 0)
      ),
    [controller]
  );

  const setPage = (pageNumber: number) => {
    controller.selectPage(pageNumber);
  };

  return (
    <Box>
      <Typography gutterBottom>Current page</Typography>
      <Pagination
        page={state.currentPage}
        count={state.maxPage}
        onChange={(e, page) => setPage(page)}
        shape="rounded"
        size="small"
      />
    </Box>
  );
};

const Pager = () => {
  const engine = useContext(EngineContext)!;
  const controller = buildPager(engine, {
    options: {numberOfPages: 3},
  });

  return <PagerRenderer controller={controller} />;
};

export default Pager;

// packages/vue-cli-plugin-coveo/generator/template/src/components/Pager.vue
<template>
  <b-pagination
    :current="state.currentPage"
    :total="state.total"
    :per-page="10"
    :range-after="5"
    :range-before="5"
    @change="onChange"
  />
</template>
<script>
import {buildPager} from '@coveo/headless';
import engine from '../Engine';
export default {
  name: 'Pager',
  data: function () {
    return {state: {}};
  },
  methods: {
    onChange: function (n) {
      this.pager.selectPage(n);
    },
  },
  created: function () {
    this.pager = buildPager(engine);
    this.pager.subscribe(() => {
      this.state = {
        ...this.pager.state,
        total: engine.state.search.response.totalCountFiltered,
      };
    });
  },
};
</script>
