// packages/cra-template/template/src/Components/Pager.tsx
import React from 'react';
import {Pagination} from '@material-ui/lab';
import Box from '@material-ui/core/Box';
import Typography from '@material-ui/core/Typography';
import {buildPager, PagerState, Pager as PagerType} from '@coveo/headless';
import {headlessEngine} from '../Engine';

export default class Pager extends React.Component {
  private headlessPager: PagerType;
  state: PagerState;

  constructor(props: any) {
    super(props);

    this.headlessPager = buildPager(headlessEngine, {
      options: {numberOfPages: 3},
    });

    this.state = this.headlessPager.state;
  }

  componentDidMount() {
    this.headlessPager.subscribe(() => this.updateState());
  }

  updateState() {
    this.setState(this.headlessPager.state);
  }

  setPage(pageNumber: number) {
    this.headlessPager.selectPage(pageNumber);
  }

  get page() {
    return this.headlessPager.state.currentPage;
  }

  get count() {
    return this.headlessPager.state.maxPage;
  }

  render() {
    return (
      <Box>
        <Typography gutterBottom>Current page</Typography>
        <Pagination
          page={this.page}
          count={this.count}
          onChange={(e, page) => this.setPage(page)}
          variant="outlined"
          shape="rounded"
          size="small"
        />
      </Box>
    );
  }
}

// packages/angular/src/ng-add-setup-project/files/src/app/pager/pager.component.ts
import {Component, OnInit} from '@angular/core';
import {PageEvent} from '@angular/material/paginator';
import {
  buildPager,
  buildResultsPerPage,
  Pager,
  PagerState,
  ResultsPerPage,
  ResultsPerPageState,
} from '@coveo/headless';
import {engine} from '../engine';

@Component({
  selector: 'app-pager',
  templateUrl: './pager.component.html',
  styleUrls: ['./pager.component.css'],
})
export class PagerComponent implements OnInit {
  private headlessPager: Pager;
  private headlessResultPerPage: ResultsPerPage;

  constructor() {}

  get pager(): PagerState {
    return this.headlessPager.state;
  }

  get resultPerPage(): ResultsPerPageState {
    return this.headlessResultPerPage.state;
  }

  onPageEvent(event: PageEvent) {
    if (!this.headlessResultPerPage.isSetTo(event.pageSize)) {
      // If page size change
      this.headlessResultPerPage.set(event.pageSize);
      this;
    } else {
      this.headlessPager.selectPage(event.pageIndex + 1);
    }
  }

  get pageSize() {
    return this.resultPerPage.numberOfResults;
  }

  get pageCount() {
    return this.pager.maxPage;
  }

  get pageIndex() {
    return this.pager.currentPage - 1;
  }

  private initializeControllers() {
    this.headlessPager = buildPager(engine, {
      options: {numberOfPages: 3},
    });

    this.headlessResultPerPage = buildResultsPerPage(engine, {
      initialState: {numberOfResults: 10},
    });
  }

  ngOnInit(): void {
    this.initializeControllers();
  }
}

<mat-paginator
  [length]="pageCount"
  [pageSize]="pageSize"
  [pageSizeOptions]="[5, 10, 25]"
  [pageIndex]="pageIndex"
  (page)="onPageEvent($event)"
>
</mat-paginator>
