// packages/vue-cli-plugin-coveo/generator/template/src/components/SearchBox.vue
<template>
  <b-autocomplete
    icon="magnify"
    placeholder="Search"
    :clearable="true"
    :data="suggestions"
    :open-on-focus="true"
    @typing="onTyping"
    @select="onSelect"
    @keydown.native="onKeyDown"
  ></b-autocomplete>
</template>

<script>
import engine from '../Engine';
import {buildSearchBox, SearchBoxOptions} from '@coveo/headless';

export default {
  name: 'SearchBox',
  data: function () {
    return {
      state: {},
    };
  },
  methods: {
    onTyping: function (v) {
      this.searchBox.updateText(v);
    },
    onSelect: function (v) {
      this.searchBox.selectSuggestion(v);
    },
    onKeyDown: function (e) {
      if (e.keyCode === 13) {
        this.searchBox.submit();
      }
    },
  },
  computed: {
    suggestions: function () {
      return this.state.suggestions.map((s) => s.rawValue);
    },
  },
  created: function () {
    const options = {
      numberOfSuggestions: 5,
    };
    this.searchBox = buildSearchBox(engine, {options});
    this.unsubscribe = this.searchBox.subscribe(() => {
      this.state = {...this.searchBox.state};
    });
  },
};
</script>

// packages/ui/angular/src/ng-add-setup-project/files/src/app/search-box/search-box.component.ts
import {Component, OnInit} from '@angular/core';
import {buildSearchBox, SearchBox, SearchBoxOptions} from '@coveo/headless';
import {FormControl} from '@angular/forms';
import {EngineService} from '../engine.service';

@Component({
  selector: 'app-search-box',
  templateUrl: './search-box.component.html',
  styleUrls: ['./search-box.component.scss'],
})
export class SearchBoxComponent implements OnInit {
  public headlessSearchBox!: SearchBox;
  public myControl = new FormControl();
  public suggestions: {
    highlightedValue: string;
    rawValue: string;
  }[] = [];

  public constructor(private engineService: EngineService) {}

  public updateState() {
    this.suggestions = this.headlessSearchBox.state.suggestions;
  }

  public onSelect(value: string) {
    this.headlessSearchBox.selectSuggestion(value);
  }

  public onInput() {
    this.headlessSearchBox.updateText(this.myControl.value);
  }

  public search() {
    if (!this.headlessSearchBox.state.isLoading) {
      this.headlessSearchBox.submit();
    }
  }

  private initializeController() {
    const options: SearchBoxOptions = {
      numberOfSuggestions: 3,
    };

    this.headlessSearchBox = buildSearchBox(this.engineService.get(), {
      options,
    });
  }

  public ngOnInit() {
    this.initializeController();
    this.headlessSearchBox.subscribe(() => this.updateState());
  }
}
