// packages/vue-cli-plugin-coveo/generator/template/src/App.vue
<template>
  <div id="app">
    <div class="hero is-primary is-medium">
      <Hero msg="Welcome to Your Coveo Vue.js Search Page" />
    </div>
    <SearchPage />
  </div>
</template>

<script lang="ts">
import {Component, Vue} from 'vue-property-decorator';
import Hero from './components/Hero.vue';
import SearchPage from './components/SearchPage.vue';

@Component({
  components: {
    Hero,
    SearchPage,
  },
})
export default class App extends Vue {}
</script>

<style lang="scss">
#app {
  font-family: $family-primary;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: $primary !important;
}
</style>

// packages/cra-template-coveo/template/src/App.tsx
import SearchPage from './Components/SearchPage';
import Hero from './Components/Hero';
import logo from './logo.svg';

function App() {
  return (
    <div className="App">
      <Hero logo={logo} welcome="Welcome to Your Coveo React.js Search Page" />
      <SearchPage />
    </div>
  );
}

export default App;
