// packages/cra-template/template/src/Components/QuerySummary.tsx
import React from 'react';
import {
  buildQuerySummary,
  QuerySummaryState,
  QuerySummary as QuerySummaryType,
} from '@coveo/headless';
import {headlessEngine} from '../Engine';
import {Box, Divider} from '@material-ui/core';

export default class QuerySummary extends React.Component {
  private headlessQuerySummary: QuerySummaryType;
  state: QuerySummaryState;

  constructor(props: {}) {
    super(props);

    this.headlessQuerySummary = buildQuerySummary(headlessEngine);

    this.state = this.headlessQuerySummary.state;
  }

  componentDidMount() {
    this.headlessQuerySummary.subscribe(() => this.updateState());
  }

  updateState() {
    this.setState(this.headlessQuerySummary.state);
  }

  renderNoResults() {
    return <Box mt={5}>No results</Box>;
  }

  renderBold(input: string) {
    return (
      <Box component="span">
        <strong>{input}</strong>
      </Box>
    );
  }

  renderRange() {
    return this.renderBold(
      ` ${this.state.firstResult}-${this.state.lastResult}`
    );
  }

  renderTotal() {
    return (
      <Box component="span">
        {' '}
        of {this.renderBold(this.state.total.toString())}
      </Box>
    );
  }

  renderQuery() {
    if (this.state.hasQuery) {
      return (
        <Box component="span"> for {this.renderBold(this.state.query)}</Box>
      );
    }
  }

  renderDuration() {
    return ` in ${this.state.durationInSeconds} seconds`;
  }

  renderHasResults() {
    return (
      <Box>
        <Box fontWeight="fontWeightBold">
          Results{this.renderRange()}
          {this.renderTotal()}
          {this.renderQuery()}
          {this.renderDuration()}
        </Box>
        <Divider />
      </Box>
    );
  }

  render() {
    if (!this.state.hasResults) {
      return this.renderNoResults();
    }
    return this.renderHasResults();
  }
}

// packages/angular/src/ng-add-setup-project/files/src/app/query-summary/query-summary.component.ts
import {Component, OnInit} from '@angular/core';
import {
  buildQuerySummary,
  QuerySummary,
  QuerySummaryState,
} from '@coveo/headless';
import {engine} from '../engine';

@Component({
  selector: 'app-query-summary',
  templateUrl: './query-summary.component.html',
  styleUrls: ['./query-summary.component.scss'],
})
export class QuerySummaryComponent implements OnInit {
  private headlessQuerySummary: QuerySummary;
  // state: QuerySummaryState;

  constructor() {}

  // private updateState() {
  //   this.state = this.headlessQuerySummary.state;
  // }

  get state(): QuerySummaryState {
    return this.headlessQuerySummary.state;
  }

  ngOnInit(): void {
    this.headlessQuerySummary = buildQuerySummary(engine);
    // this.headlessQuerySummary.subscribe(() => this.updateState());
  }
}

<div *ngIf="state.hasResults; else noResultBlock">
  Results
  <b>{{ state.firstResult }}-{{ state.lastResult }}</b> of {{ state.total }} for
  <b>{{ state.query }}</b> in {{ state.durationInSeconds }} seconds
  <!-- TODO: add numeric directive to format number -->
</div>

<ng-template #noResultBlock>
  No results for <b>{{ state.query }}</b>
</ng-template>
