// packages/angular/src/ng-add-setup-project/files/src/app/facet-list/facet-list.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-facet-list',
  templateUrl: './facet-list.component.html',
  styleUrls: ['./facet-list.component.css'],
})
export class FacetListComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<p>Refine By</p>
<app-facet field="objecttype" title="Object Type"></app-facet>
<app-facet field="filetype" title="File Type"></app-facet>
<app-facet field="author" title="Author"></app-facet>

// packages/cra-template/template/src/Components/FacetList.tsx
import Typography from '@material-ui/core/Typography';
import Box from '@material-ui/core/Box';
import Facet from './Facet';

const FacetList = () => {
  return (
    <Box>
      <Box px={1} pb={1}>
        <Typography variant="overline">Refine By</Typography>
        <Facet field="objecttype" title="Object Type" />
        <Facet field="filetype" title="File Type" />
        <Facet field="author" title="Author" />
      </Box>
    </Box>
  );
};

export default FacetList;
