// packages/angular/src/ng-add-setup-project/files/src/app/facet/facet.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {MatSelectionListChange} from '@angular/material/list';
import {buildFacet, Facet, FacetValue} from '@coveo/headless';
import {engine} from '../engine';

@Component({
  selector: 'app-facet',
  templateUrl: './facet.component.html',
  styleUrls: ['./facet.component.scss'],
})
export class FacetComponent implements OnInit {
  @Input() field: string;
  @Input() title: string;

  private headlessFacet: Facet;

  constructor() {}

  selectionChange(change: MatSelectionListChange) {
    change.options.forEach((option) => {
      this.headlessFacet.toggleSelect(option.value);
    });
  }

  showMore() {
    this.headlessFacet.showMoreValues();
  }

  showLess() {
    this.headlessFacet.showLessValues();
  }

  canShowLess() {
    return this.headlessFacet.state.canShowLessValues;
  }

  canShowMore() {
    return this.headlessFacet.state.canShowMoreValues;
  }

  isFacetValueSelected(value: FacetValue): boolean {
    return this.headlessFacet.isValueSelected(value);
  }

  get facetValues(): FacetValue[] {
    return this.headlessFacet.state.values;
  }

  private initializeController() {
    this.headlessFacet = buildFacet(engine, {
      options: {
        numberOfValues: 5,
        field: this.field,
      },
    });
  }

  ngOnInit(): void {
    this.initializeController();

    // this.facet.subscribe(() => this.updateState());
  }
}

<div *ngIf="facetValues.length > 0">
  <p class="mat-subheading-2 pl-2">{{ this.title }}</p>

  <mat-selection-list dense (selectionChange)="selectionChange($event)">
    <mat-list-option
      *ngFor="let facetValue of facetValues"
      [value]="facetValue"
      [selected]="isFacetValueSelected(facetValue)"
      checkboxPosition="before"
    >
      <div class="space-between">
        <div class="mat-body-1">
          {{ facetValue.value }}
        </div>
        <div class="mat-caption">({{ facetValue.numberOfResults }})</div>
      </div>
    </mat-list-option>
  </mat-selection-list>

  <div *ngIf="canShowLess()">
    <button mat-button color="primary" (click)="showLess()">Show Less</button>
  </div>

  <div *ngIf="canShowMore()">
    <button mat-button color="primary" (click)="showMore()">Show More</button>
  </div>
</div>

// packages/cra-template/template/src/Components/Facet.tsx
import React from 'react';
import {
  Facet as FacetType,
  FacetState,
  buildFacet,
  FacetValue,
} from '@coveo/headless';
import {headlessEngine} from '../Engine';
import Button from '@material-ui/core/Button';
import Checkbox from '@material-ui/core/Checkbox';
import Box from '@material-ui/core/Box';
import List from '@material-ui/core/List';
import './Facet.css';
import {Divider, ListItem, ListItemText, Typography} from '@material-ui/core';

interface IFacetProps {
  title: string;
  field: string;
}

export default class Facet extends React.Component<IFacetProps, {}> {
  private headlessFacet: FacetType;
  state: FacetState;

  constructor(props: IFacetProps) {
    super(props);

    this.headlessFacet = buildFacet(headlessEngine, {
      options: {
        numberOfValues: 5,
        field: this.props.field,
      },
    });

    this.state = this.headlessFacet.state;
  }

  componentDidMount() {
    this.headlessFacet.subscribe(() => this.updateState());
  }

  componentWillUnmount() {
    this.headlessFacet.subscribe(() => {});
  }

  updateState() {
    this.setState(this.headlessFacet.state);
  }

  toggleSelect(value: FacetValue) {
    this.headlessFacet.toggleSelect(value);
  }

  showMore() {
    this.headlessFacet.showMoreValues();
  }

  showLess() {
    this.headlessFacet.showLessValues();
  }

  render() {
    return (
      <Box mb={5} mr={3} p={1}>
        <Box pb={1}>
          <Typography variant="h6" component="h6">
            {this.props.title}
          </Typography>
        </Box>
        <Divider />
        <List dense>
          {this.state.values.map((value: FacetValue) => {
            const labelId = `checkbox-list-label-${value}`;

            return (
              <ListItem
                style={{padding: 0}}
                key={value.value}
                role={undefined}
                button
                onClick={() => this.toggleSelect(value)}
              >
                <Checkbox
                  size="small"
                  edge="start"
                  checked={this.headlessFacet.isValueSelected(value)}
                  tabIndex={-1}
                  disableRipple
                  inputProps={{'aria-labelledby': labelId}}
                />
                <ListItemText
                  className="truncate inline"
                  primary={`${value.value}`}
                  secondary={`(${value.numberOfResults})`}
                />
              </ListItem>
            );
          })}
        </List>
        {this.state.canShowLessValues && (
          <Button size="small" onClick={() => this.showLess()}>
            Show Less
          </Button>
        )}
        {this.state.canShowMoreValues && (
          <Button size="small" onClick={() => this.showMore()}>
            Show More
          </Button>
        )}
      </Box>
    );
  }
}
