// packages/angular/src/ng-add-setup-project/files/src/app/result-list/result-list.component.ts
import {Component, OnInit} from '@angular/core';
import {buildResultList, Result, ResultList} from '@coveo/headless';
import {engine} from '../engine';

@Component({
  selector: 'app-result-list',
  templateUrl: './result-list.component.html',
  styleUrls: ['./result-list.component.scss'],
})
export class ResultListComponent implements OnInit {
  private headlessResultList!: ResultList;

  constructor() {}

  get results(): Result[] {
    return this.headlessResultList.state.results;
  }

  private initializeController() {
    this.headlessResultList = buildResultList(engine);
  }

  ngOnInit(): void {
    this.initializeController();
  }
}

<div *ngFor="let result of results">
  <div class="mb-5">
    <div class="mb-2">
      <a href="{{ result.clickUri }}">{{ result.title }}</a>
    </div>

    <div class="mb-1">
      <div class="mat-body-1">{{ result.excerpt }}</div>
    </div>

    <div class="flex-row">
      <div class="mr-4">
        <div *ngIf="result.raw.source" class="mat-caption">
          <span class="mr-1">Source</span>
          <span>{{ result.raw.source }}</span>
        </div>
      </div>
      <div class="mr-4">
        <div *ngIf="result.raw.objecttype" class="mat-caption">
          <span class="mr-1">Object Type</span>
          <span>{{ result.raw.objecttype }}</span>
        </div>
      </div>
    </div>
  </div>
</div>

// packages/cra-template/template/src/Components/ResultList.tsx
import React from 'react';
import List from '@material-ui/core/List';
import {ListItem, Box, Typography} from '@material-ui/core';
import {
  buildResultList,
  ResultTemplatesManager,
  Result,
  ResultListState,
  ResultList as ResultListType,
  buildResultTemplatesManager,
} from '@coveo/headless';
import {IEngineProp} from '../common/Engine';

type Template = (result: Result) => any;

interface FieldValueInterface {
  value: string;
  caption: string;
}

function ListItemLink(props: any) {
  return (
    <ListItem style={{padding: 0}} component="a" {...props}>
      <Typography variant="body1" color="primary">
        {props.title}
      </Typography>
    </ListItem>
  );
}

function FieldValue(props: FieldValueInterface) {
  return (
    <Box>
      <Typography
        color="textSecondary"
        style={{fontWeight: 'bold'}}
        variant="caption"
      >
        {props.caption}:&nbsp;
      </Typography>
      <Typography color="textSecondary" variant="caption">
        {props.value}
      </Typography>
    </Box>
  );
}

export default class ResultList extends React.Component<IEngineProp> {
  private headlessResultList: ResultListType;
  private headlessResultTemplateManager: ResultTemplatesManager<Template>;
  state: ResultListState;

  constructor(props: any) {
    super(props);

    this.headlessResultList = buildResultList(this.props.engine);

    this.state = this.headlessResultList.state;

    this.headlessResultTemplateManager = buildResultTemplatesManager(
      this.props.engine
    );
    this.headlessResultTemplateManager.registerTemplates({
      conditions: [],
      content: (result: Result) => (
        <ListItem disableGutters key={result.uniqueId}>
          <Box my={2}>
            <Box pb={1}>
              <ListItemLink
                disableGutters
                title={result.title}
                href={result.clickUri}
              />
            </Box>

            {result.excerpt && (
              <Box pb={1}>
                <Typography color="textPrimary" variant="body2">
                  {result.excerpt}
                </Typography>
              </Box>
            )}

            {result.raw.source && (
              <FieldValue caption="Source" value={result.raw.source} />
            )}
            {result.raw.objecttype && (
              <FieldValue caption="Object Type" value={result.raw.objecttype} />
            )}
          </Box>
        </ListItem>
      ),
    });
  }

  componentDidMount() {
    this.headlessResultList.subscribe(() => this.updateState());
  }

  updateState() {
    this.setState(this.headlessResultList.state);
  }

  render() {
    return (
      <List>
        {this.state.results.map((result: Result) => {
          const template = this.headlessResultTemplateManager.selectTemplate(
            result
          );
          return template ? template(result) : null;
        })}
      </List>
    );
  }
}
