// packages/angular/src/ng-add-setup-project/files/src/app/search-page/search-page.component.ts
import {Component, AfterViewInit} from '@angular/core';
import {AnalyticsActions, SearchActions} from '@coveo/headless';
import {EngineService} from '../engine.service';

@Component({
  selector: 'app-search-page',
  templateUrl: './search-page.component.html',
  styleUrls: ['./search-page.component.scss'],
})
export class SearchPageComponent implements AfterViewInit {
  constructor(private engine: EngineService) {}

  executeSearch() {
    const {dispatch} = this.engine.get();
    const action = SearchActions.executeSearch(
      AnalyticsActions.logInterfaceLoad()
    );
    dispatch(action);
  }

  ngAfterViewInit(): void {
    this.executeSearch();
  }
}

<div class="row center-xs">
  <div class="col-xs-12 col-sm-8 mb-5">
    <app-search-box></app-search-box>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-3">
    <app-facet-list></app-facet-list>
  </div>
  <div class="col-xs-12 col-sm-9 pl-3">
    <div class="row mb-4 flex-center between-xs">
      <div class="col-xs-6">
        <app-query-summary></app-query-summary>
      </div>
      <div class="col-xs-6 end-xs">
        <app-sort></app-sort>
      </div>
    </div>
    <app-result-list></app-result-list>
    <app-pager></app-pager>
  </div>
</div>

// packages/cra-template/template/src/Components/SearchPage.tsx
import React from 'react';
import Container from '@material-ui/core/Container';
import Box from '@material-ui/core/Box';
import Grid from '@material-ui/core/Grid';
import SearchBox from './SearchBox';
import QuerySummary from './QuerySummary';
import ResultList from './ResultList';
import Pager from './Pager';
import Sort from './Sort';
import FacetList from './FacetList';
import ResultsPerPage from './ResultsPerPage';
import {AnalyticsActions, SearchActions} from '@coveo/headless';
import {headlessEngine} from '../Engine';

export default class SearchPage extends React.Component {
  componentDidMount() {
    const {dispatch} = headlessEngine;
    const action = SearchActions.executeSearch(
      AnalyticsActions.logInterfaceLoad()
    ) as any;
    dispatch(action);
  }

  render() {
    return (
      <Container maxWidth="lg">
        <Grid container justify="center">
          <Grid item md={8}>
            <SearchBox />
          </Grid>
        </Grid>

        <Box my={4}>
          <Grid container>
            <Grid item md={3} sm={12}>
              <FacetList />
            </Grid>
            <Grid item md={9} sm={12}>
              <Box pl={3}>
                <Grid container alignItems="flex-end">
                  <Grid item md={10}>
                    <QuerySummary />
                  </Grid>
                  <Grid item md={2}>
                    <Sort />
                  </Grid>
                </Grid>
                <ResultList />
              </Box>
              <Box my={4}>
                <Grid container>
                  <Grid item md={6}>
                    <Pager />
                  </Grid>
                  <Grid item md={6}>
                    <ResultsPerPage />
                  </Grid>
                </Grid>
              </Box>
            </Grid>
          </Grid>
        </Box>
      </Container>
    );
  }
}
